pub mod chapter_card;
pub mod composited_effects;
pub mod compute;
pub mod compositor;
pub mod effects;
pub mod endcard;
pub mod ffmpeg;
pub mod glsl_compat;
pub mod gpu;
pub mod intro;
pub mod manifest;
pub mod motion_blur;
pub mod overlay_atlas;
pub mod overlay_cache;
pub mod overlay_pass;
pub mod postprocess;
pub mod temporal;
pub mod text_layers;
pub mod transition;
pub mod uniforms;

/// Codegen-emitted uniform layout (Wave 2.1 phase C).
/// Generated by `npx tsx packages/renderer/scripts/generate-rust-uniforms.mts`
/// from `packages/renderer/uniforms-schema.json`.
#[path = "../generated/uniforms_layout.rs"]
pub mod uniforms_layout;
