//! Dead Air GPU Renderer — renders GLSL shaders directly on GPU via wgpu.
//!
//! Hybrid architecture:
//!   1. Node.js pre-pass generates frame manifests (shader choice, uniforms per frame)
//!   2. This Rust program renders shaders at native GPU speed
//!   3. Overlay compositing handled separately
//!
//! Usage:
//!   dead-air-renderer --manifest manifest.json --output-dir ./frames --width 3840 --height 2160

mod gpu;
mod manifest;
mod shader_cache;
mod uniforms;

use clap::Parser;
use indicatif::{ProgressBar, ProgressStyle};
use std::path::PathBuf;
use std::time::Instant;

#[derive(Parser, Debug)]
#[command(name = "dead-air-renderer", about = "GPU-native GLSL shader renderer")]
struct Args {
    /// Path to frame manifest JSON (generated by Node.js pre-pass)
    #[arg(short, long)]
    manifest: PathBuf,

    /// Output directory for rendered frames (PNG)
    #[arg(short, long, default_value = "./frames")]
    output_dir: PathBuf,

    /// Render width in pixels
    #[arg(long, default_value_t = 3840)]
    width: u32,

    /// Render height in pixels
    #[arg(long, default_value_t = 2160)]
    height: u32,

    /// Frames per second
    #[arg(long, default_value_t = 60)]
    fps: u32,

    /// Start frame (for partial renders)
    #[arg(long, default_value_t = 0)]
    start_frame: u32,

    /// End frame (0 = render all)
    #[arg(long, default_value_t = 0)]
    end_frame: u32,
}

fn main() {
    env_logger::init();
    let args = Args::parse();

    // Create output directory
    std::fs::create_dir_all(&args.output_dir).expect("Failed to create output directory");

    // Load manifest
    println!("Loading manifest: {}", args.manifest.display());
    let manifest = manifest::load_manifest(&args.manifest)
        .expect("Failed to load manifest");

    let total_frames = if args.end_frame > 0 {
        (args.end_frame - args.start_frame) as usize
    } else {
        manifest.frames.len() - args.start_frame as usize
    };

    println!(
        "Rendering {} frames at {}x{} @ {}fps",
        total_frames, args.width, args.height, args.fps
    );

    // Initialize GPU
    let start = Instant::now();
    let mut renderer = pollster::block_on(gpu::GpuRenderer::new(args.width, args.height))
        .expect("Failed to initialize GPU renderer");

    println!(
        "GPU initialized: {} in {:.2}s",
        renderer.adapter_name(),
        start.elapsed().as_secs_f64()
    );

    // Compile shaders
    let mut shader_cache = shader_cache::ShaderCache::new();
    let unique_shaders: std::collections::HashSet<&str> = manifest
        .frames
        .iter()
        .map(|f| f.shader_id.as_str())
        .collect();

    println!("Compiling {} unique shaders...", unique_shaders.len());
    for shader_id in &unique_shaders {
        if let Some(glsl_source) = manifest.shaders.get(*shader_id) {
            match shader_cache.compile(&renderer, shader_id, glsl_source) {
                Ok(_) => log::debug!("Compiled: {}", shader_id),
                Err(e) => {
                    log::error!("Failed to compile {}: {}", shader_id, e);
                    eprintln!("WARNING: Shader {} failed to compile: {}", shader_id, e);
                }
            }
        }
    }
    println!("Shader compilation complete.");

    // Render loop
    let progress = ProgressBar::new(total_frames as u64);
    progress.set_style(
        ProgressStyle::with_template(
            "{spinner:.green} [{elapsed_precise}] [{bar:50.cyan/blue}] {pos}/{len} ({per_sec}, ETA: {eta})",
        )
        .unwrap()
        .progress_chars("=>-"),
    );

    let start_idx = args.start_frame as usize;
    let end_idx = if args.end_frame > 0 {
        args.end_frame as usize
    } else {
        manifest.frames.len()
    };

    for frame_idx in start_idx..end_idx {
        let frame = &manifest.frames[frame_idx];

        // Get compiled shader pipeline
        let pipeline = match shader_cache.get_pipeline(&frame.shader_id) {
            Some(p) => p,
            None => {
                log::warn!(
                    "No pipeline for shader {}, skipping frame {}",
                    frame.shader_id,
                    frame_idx
                );
                progress.inc(1);
                continue;
            }
        };

        // Build uniform buffer from frame data
        let uniform_data = uniforms::build_uniform_buffer(frame, args.width, args.height);

        // Render frame to texture
        renderer.render_frame(pipeline, &uniform_data);

        // Read back pixels and save as PNG
        let pixels = renderer.read_pixels();
        let output_path = args.output_dir.join(format!("frame_{:07}.png", frame_idx));
        image::save_buffer(
            &output_path,
            &pixels,
            args.width,
            args.height,
            image::ColorType::Rgba8,
        )
        .expect("Failed to save frame");

        progress.inc(1);
    }

    progress.finish_with_message("Render complete");

    let elapsed = start.elapsed();
    let fps_actual = total_frames as f64 / elapsed.as_secs_f64();
    println!(
        "\nRendered {} frames in {:.1}s ({:.1} fps, {:.3}s/frame)",
        total_frames,
        elapsed.as_secs_f64(),
        fps_actual,
        elapsed.as_secs_f64() / total_frames as f64,
    );
}
