/**
 * Mountain Fire — raymarched volcanic mountain erupting.
 * Full mountain SDF with eruption crater, lava flows down slopes,
 * pyroclastic cloud expanding, ash fall particles, orange-lit landscape.
 * Exterior volcanic scene (different from inferno which is cavern interior).
 *
 * Audio reactivity:
 *   uBass             → lava pulse, ground tremor
 *   uEnergy           → eruption intensity, lava flow speed
 *   uDrumOnset        → eruption burst, pyroclastic surge
 *   uVocalPresence    → lava glow warmth
 *   uHarmonicTension  → lava color shift (orange→red→magenta)
 *   uBeatSnap         → ash burst
 *   uSectionType      → jam=full eruption, space=smoldering, solo=lava river focus
 *   uClimaxPhase      → catastrophic eruption
 *   uSlowEnergy       → smoke column height
 *   uHighs            → ash particle detail
 *   uMelodicPitch     → mountain height shift
 *   uChromaHue        → fire/lava color cycling
 *   uPalettePrimary   → lava base hue
 *   uPaletteSecondary → sky/smoke accent
 *   uSpectralFlux     → eruption turbulence
 *   uDynamicRange     → light/shadow contrast
 */

import { noiseGLSL } from "./noise";
import { sharedUniformsGLSL } from "./shared/uniforms.glsl";
import { buildPostProcessGLSL } from "./shared/postprocess.glsl";
import { buildRaymarchNormal, buildRaymarchAO, buildDepthAlphaOutput } from "./shared/raymarching.glsl";
import { lightingGLSL } from "./shared/lighting.glsl";

export const mountainFireVert = /* glsl */ `
varying vec2 vUv;
void main() {
  vUv = uv;
  gl_Position = vec4(position, 1.0);
}
`;

const mfNormalGLSL = buildRaymarchNormal("mfMap($P, melPitch, timeVal, bass)", { eps: 0.01, name: "mfNormal" });
const mfAOGLSL = buildRaymarchAO("mfMap($P, melPitch, timeVal, bass)", { steps: 5, stepBase: 0.02, stepScale: 0.08, weightDecay: 0.6, finalMult: 2.0, name: "mfAO" });
const mfDepthAlpha = buildDepthAlphaOutput("marchDist", "MAX_DIST");

export const mountainFireFrag = /* glsl */ `
precision highp float;

${sharedUniformsGLSL}

${noiseGLSL}

${lightingGLSL}

${buildPostProcessGLSL({
  grainStrength: "normal",
  bloomEnabled: true,
  bloomThresholdOffset: -0.1,
  halationEnabled: true,
  caEnabled: true,
  lensDistortionEnabled: true,
  beatPulseEnabled: true,
})}

varying vec2 vUv;

#define PI 3.14159265
#define TAU 6.28318530
#define MAX_STEPS 80
#define MAX_DIST 50.0
#define SURF_DIST 0.003
#define ASH_COUNT 24

// ============================================================
// Prefixed utilities (mf = mountain fire)
// ============================================================
mat2 mfRot2(float a) {
  float c = cos(a), s = sin(a);
  return mat2(c, -s, s, c);
}

float mfHash(float n) { return fract(sin(n) * 43758.5453123); }
float mfHash2(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
vec3 mfHash3(float n) {
  return vec3(
    fract(sin(n * 127.1) * 43758.5453),
    fract(sin(n * 269.5) * 43758.5453),
    fract(sin(n * 419.2) * 43758.5453)
  );
}

// ============================================================
// SDF primitives
// ============================================================
float mfSDSphere(vec3 pos, float radius) { return length(pos) - radius; }

float mfSDCone(vec3 pos, float radius, float height) {
  vec2 q = vec2(length(pos.xz), pos.y);
  vec2 tip = vec2(0.0, height);
  vec2 baseEdge = vec2(radius, 0.0);
  vec2 ba = baseEdge - tip;
  vec2 pa = q - tip;
  float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
  float d = length(pa - ba * h);
  float signD = sign(pa.x * ba.y - pa.y * ba.x);
  return max(d * signD, -pos.y);
}

float mfSDPlane(vec3 pos, float yLevel) { return pos.y - yLevel; }

float mfSmin(float a, float b, float k) {
  float h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
  return mix(b, a, h) - k * h * (1.0 - h);
}

// ============================================================
// Volcanic mountain terrain
// ============================================================
float mfMountainHeight(vec2 xz, float melPitch) {
  float dist = length(xz);
  // Central volcanic cone
  float cone = max(0.0, 8.0 + melPitch * 1.5 - dist * 0.6);
  // Crater depression at top
  float crater = smoothstep(1.5, 0.0, dist) * 2.0;
  cone -= crater;
  // Noise displacement for rocky texture
  cone += snoise(vec3(xz * 0.3, 0.0)) * 1.0;
  cone += snoise(vec3(xz * 0.8, 5.0)) * 0.4;
  cone += snoise(vec3(xz * 2.0, 10.0)) * 0.12;
  // Surrounding terrain: low hills
  float surroundH = snoise(vec3(xz * 0.05, 20.0)) * 2.0;
  surroundH += snoise(vec3(xz * 0.15, 25.0)) * 0.8;
  float surroundMask = smoothstep(12.0, 20.0, dist);
  cone = mix(cone, max(surroundH, 0.0), surroundMask);
  return max(cone, 0.0);
}

float mfMap(vec3 pos, float melPitch, float timeVal, float bass) {
  float terrainH = mfMountainHeight(pos.xz, melPitch);
  // Bass tremor
  terrainH += sin(pos.x * 0.5 + timeVal * 2.0) * bass * 0.1;
  return pos.y - terrainH;
}

// Normal & AO — generated by shared raymarching utilities
${mfNormalGLSL}
${mfAOGLSL}

// ============================================================
// Soft shadow
// ============================================================
float mfSoftShadow(vec3 ro, vec3 rd, float mint, float maxt,
                   float melPitch, float timeVal, float bass) {
  float res = 1.0;
  float tSh = mint;
  for (int i = 0; i < 32; i++) {
    float h = mfMap(ro + rd * tSh, melPitch, timeVal, bass);
    res = min(res, 8.0 * h / tSh);
    tSh += clamp(h, 0.02, 0.5);
    if (h < 0.001 || tSh > maxt) break;
  }
  return clamp(res, 0.0, 1.0);
}

// ============================================================
// Lava flow patterns on mountain slope
// ============================================================
float mfLavaFlow(vec3 pos, float timeVal, float energy, float bass) {
  float dist = length(pos.xz);
  // Lava flows radially from crater
  float flowMask = smoothstep(3.0, 0.5, dist) * smoothstep(0.0, 1.0, pos.y);

  // Channel pattern: noise creates river-like paths
  float channelAngle = atan(pos.z, pos.x);
  float channelNoise = snoise(vec3(channelAngle * 2.0, pos.y * 0.5, 0.0));
  float channel = smoothstep(0.3, 0.6, channelNoise);

  // Flow animation: advect downward
  float flowSpeed = 0.3 + energy * 0.5;
  float flowNoise = fbm3(vec3(pos.xz * 0.3, pos.y * 0.5 + timeVal * flowSpeed));
  float flow = flowMask * channel * (flowNoise * 0.5 + 0.5);

  // Bass pulse makes lava surge
  flow *= 1.0 + bass * 0.5;

  return clamp(flow * energy, 0.0, 1.0);
}

// ============================================================
// Lava color
// ============================================================
vec3 mfLavaColor(float intensity, float tension, float chromaH) {
  vec3 coolLava = vec3(0.6, 0.1, 0.0);
  vec3 hotLava = vec3(1.0, 0.5, 0.05);
  vec3 whiteHot = vec3(1.0, 0.9, 0.6);

  vec3 col = mix(coolLava, hotLava, smoothstep(0.0, 0.5, intensity));
  col = mix(col, whiteHot, smoothstep(0.5, 1.0, intensity) * 0.4);
  col = mix(col, col * vec3(1.0, 0.6, 0.4), tension * 0.3);
  col.r += chromaH * 0.1;
  return col;
}

// ============================================================
// Pyroclastic cloud (volumetric eruption plume)
// ============================================================
vec3 mfPyroclasticCloud(vec3 ro, vec3 rd, float marchDist, float timeVal,
                        float energy, float flux, float slowE, vec3 palCol1) {
  vec3 cloud = vec3(0.0);
  float eruptionHeight = 8.0 + energy * 6.0 + slowE * 3.0;
  float stepSize = 0.5;

  for (int i = 0; i < 32; i++) {
    float tC = float(i) * stepSize + 2.0;
    if (tC > marchDist) break;
    vec3 cPos = ro + rd * tC;

    // Plume shape: expands as it rises from crater
    float craterDist = length(cPos.xz);
    float heightFrac = (cPos.y - 6.0) / eruptionHeight;
    if (heightFrac < 0.0 || heightFrac > 1.0) continue;

    float plumeRadius = mix(1.0, 5.0, heightFrac);
    float plumeMask = smoothstep(plumeRadius, plumeRadius * 0.3, craterDist);
    float verticalEnv = smoothstep(0.0, 0.1, heightFrac) * smoothstep(1.0, 0.6, heightFrac);

    // Turbulent cloud noise
    vec3 cloudP = cPos;
    cloudP.y -= timeVal * 0.5;
    float cloudN = fbm3(cloudP * 0.2 + vec3(0.0, -timeVal * 0.1, 0.0));
    cloudN += fbm3(cloudP * 0.5 + 10.0) * 0.4;

    float density = plumeMask * verticalEnv * (cloudN * 0.5 + 0.5);
    density *= 0.05 * (0.5 + flux * 0.5);

    // Color: dark ash with fire undertone at base
    vec3 ashColor = mix(vec3(0.06, 0.04, 0.03), vec3(0.12, 0.08, 0.06), heightFrac);
    // Fire glow at base
    float fireGlow = (1.0 - heightFrac) * energy;
    ashColor += palCol1 * 0.1 * fireGlow;

    cloud += ashColor * density * stepSize;
  }
  return cloud;
}

// ============================================================
// Ash fall particles
// ============================================================
vec3 mfAshParticles(vec3 ro, vec3 rd, float timeVal, float energy, float highs) {
  vec3 ash = vec3(0.0);
  int count = int(mix(8.0, 24.0, energy));
  for (int i = 0; i < ASH_COUNT; i++) {
    if (i >= count) break;
    float fi = float(i);
    vec3 seed = mfHash3(fi * 5.7 + 2.0);

    // Ash drifts down slowly, swaying
    float ashLife = fract(seed.x * 2.0 + timeVal * 0.05);
    vec3 ashPos = vec3(
      (seed.y - 0.5) * 20.0 + sin(timeVal * 0.3 + fi) * 2.0,
      12.0 - ashLife * 14.0,
      (seed.z - 0.5) * 20.0 + cos(timeVal * 0.2 + fi * 1.3) * 1.5
    );

    vec3 toA = ashPos - ro;
    float proj = dot(toA, rd);
    if (proj < 0.0) continue;
    vec3 closest = ro + rd * proj;
    float dist = length(closest - ashPos);

    float ashSize = 0.015 + seed.y * 0.01;
    float glow = smoothstep(ashSize * 5.0, 0.0, dist);
    float lifeFade = smoothstep(0.0, 0.1, ashLife) * smoothstep(1.0, 0.8, ashLife);

    // Some ash glows hot (embers), most is dark
    vec3 ashCol = seed.x > 0.7 ? vec3(1.0, 0.5, 0.1) * 0.5 : vec3(0.15, 0.12, 0.1);
    ash += ashCol * glow * lifeFade * 0.15 * (0.5 + highs * 0.5);
  }
  return ash;
}

// ============================================================
// Sky: volcanic apocalypse
// ============================================================
vec3 mfSky(vec3 rd, float energy, float slowE, vec3 palCol2) {
  float skyGrad = rd.y * 0.5 + 0.5;
  vec3 skyDark = vec3(0.01, 0.01, 0.02);
  vec3 skyMid = mix(vec3(0.06, 0.02, 0.03), palCol2 * 0.1, 0.15);
  vec3 skyHot = vec3(0.15, 0.04, 0.02);

  float skyMix = smoothstep(0.1, 0.8, slowE);
  vec3 sky = mix(skyDark, skyMid, skyMix);
  sky = mix(sky, skyHot, smoothstep(0.5, 1.0, energy) * (1.0 - skyGrad));

  // Horizon fire glow
  float horizonGlow = exp(-pow(rd.y * 6.0, 2.0));
  sky += skyHot * horizonGlow * energy * 0.2;

  // Darkened sky overhead
  sky *= mix(0.5, 1.0, smoothstep(0.8, 0.0, skyGrad));

  // Stars visible when calm
  float starFade = 1.0 - smoothstep(0.15, 0.5, energy);
  if (starFade > 0.01 && rd.y > 0.1) {
    vec2 starUV = rd.xz / (rd.y + 0.001);
    float sh = mfHash2(floor(starUV * 80.0));
    if (sh > 0.9) {
      vec2 sf = fract(starUV * 80.0);
      float sd = length(sf - 0.5);
      float twinkle = 0.7 + 0.3 * sin(uTime * 2.0 + sh * 50.0);
      sky += vec3(0.8, 0.85, 1.0) * smoothstep(0.03, 0.005, sd) * twinkle * starFade * 0.3;
    }
  }

  return sky;
}

void main() {
  vec2 uv = vUv;
  vec2 aspect = vec2(uResolution.x / uResolution.y, 1.0);
  vec2 screenPos = (uv - 0.5) * aspect;

  float energy = clamp(uEnergy, 0.0, 1.0);
  float bass = clamp(uBass, 0.0, 1.0);
  float highs = clamp(uHighs, 0.0, 1.0);
  float drumOnset = clamp(uDrumOnset, 0.0, 1.0);
  float slowE = clamp(uSlowEnergy, 0.0, 1.0);
  float chromaH = clamp(uChromaHue, 0.0, 1.0);
  float flux = clamp(uSpectralFlux, 0.0, 1.0);
  float vocalP = clamp(uVocalPresence, 0.0, 1.0);
  float melPitch = clamp(uMelodicPitch, 0.0, 1.0);
  float tension = clamp(uHarmonicTension, 0.0, 1.0);
  float dynRange = clamp(uDynamicRange, 0.0, 1.0);
  float beatSnap = clamp(uBeatSnap, 0.0, 1.0);

  float sectionT = uSectionType;
  float sJam = smoothstep(4.5, 5.5, sectionT) * (1.0 - step(5.5, sectionT));
  float sSpace = smoothstep(6.5, 7.5, sectionT);
  float sSolo = smoothstep(3.5, 4.5, sectionT) * (1.0 - step(4.5, sectionT));
  float sChorus = smoothstep(1.5, 2.5, sectionT) * (1.0 - step(2.5, sectionT));

  float isClimax = step(1.5, uClimaxPhase) * step(uClimaxPhase, 3.5);
  float climaxBoost = isClimax * uClimaxIntensity;

  float timeVal = uDynamicTime * 0.12;
  float fireIntensityMod = 1.0 + sJam * 0.5 + sChorus * 0.3 - sSpace * 0.6;

  // Palette
  float hue1 = uPalettePrimary + chromaH * 0.06;
  float hue2 = uPaletteSecondary + chromaH * 0.04;
  float palSat = mix(0.5, 0.9, energy) * uPaletteSaturation;
  vec3 palCol1 = hsv2rgb(vec3(hue1, palSat, 0.9));
  vec3 palCol2 = hsv2rgb(vec3(hue2, palSat * 0.5, 0.6));

  // Camera: viewing erupting mountain from a safe distance
  float camAngle = uTime * 0.01 + sin(uTime * 0.005) * 0.3;
  float camDist = 18.0;
  float camH = 4.0 + sin(uTime * 0.04) * 0.5;
  vec3 camOrigin = vec3(cos(camAngle) * camDist, camH, sin(camAngle) * camDist);
  vec3 camTarget = vec3(0.0, 5.0, 0.0);
  vec3 camForward = normalize(camTarget - camOrigin);
  vec3 camWorldUp = vec3(0.0, 1.0, 0.0);
  vec3 camRt = normalize(cross(camForward, camWorldUp));
  vec3 camUpV = cross(camRt, camForward);

  // Camera shake from bass tremor
  float shakeX = sin(uDynamicTime * 8.0) * bass * 0.005;
  float shakeY = cos(uDynamicTime * 10.0) * bass * 0.003;

  vec3 rd = normalize((screenPos.x + shakeX) * camRt + (screenPos.y + shakeY) * camUpV + 1.5 * camForward);

  // Eruption light source (crater)
  vec3 eruptionPos = vec3(0.0, 8.0, 0.0);
  vec3 eruptionLightDir = normalize(eruptionPos);

  // ─── Raymarch terrain ───
  float marchDist = 0.0;
  float terrainHitDist = -1.0;

  for (int i = 0; i < MAX_STEPS; i++) {
    vec3 pos = camOrigin + rd * marchDist;
    float d = mfMap(pos, melPitch, timeVal, bass);
    if (d < SURF_DIST) {
      terrainHitDist = marchDist;
      break;
    }
    marchDist += d * 0.7;
    if (marchDist > MAX_DIST) break;
  }

  vec3 col;

  if (terrainHitDist < 0.0) {
    col = mfSky(rd, energy, slowE, palCol2);
  } else {
    vec3 hitPos = camOrigin + rd * terrainHitDist;
    vec3 norm = mfNormal(hitPos);
    float ambOcc = mfAO(hitPos, norm);

    // Eruption light from above
    vec3 toLava = eruptionPos - hitPos;
    float lavaDist = length(toLava);
    vec3 lavaDir = toLava / lavaDist;
    float lavaAtten = 1.0 / (1.0 + lavaDist * lavaDist * 0.01);
    float lavaDiffuse = max(dot(norm, lavaDir), 0.0) * lavaAtten;

    // Specular
    vec3 viewDir = normalize(camOrigin - hitPos);
    vec3 halfLava = normalize(lavaDir + viewDir);
    float lavaSpec = pow(max(dot(norm, halfLava), 0.0), 32.0) * lavaAtten;

    // Fresnel
    float fresnelVal = pow(1.0 - max(dot(viewDir, norm), 0.0), 3.0);

    // Shadow
    float shadow = mfSoftShadow(hitPos + norm * 0.02, lavaDir, 0.1, 15.0, melPitch, timeVal, bass);

    // ─── Lava flow pattern ───
    float lavaFlow = mfLavaFlow(hitPos, timeVal, energy, bass);
    lavaFlow *= fireIntensityMod;
    lavaFlow += drumOnset * 0.2 * smoothstep(3.0, 0.5, length(hitPos.xz)); // eruption burst
    lavaFlow = clamp(lavaFlow + climaxBoost * 0.3, 0.0, 1.0);

    // Material: dark volcanic rock + lava
    float rockN = fbm3(vec3(hitPos * 0.5));
    vec3 rockColor = mix(vec3(0.03, 0.025, 0.02), vec3(0.08, 0.06, 0.04), rockN);
    // Stratified rock bands
    float bands = sin(hitPos.y * 3.0 + snoise(vec3(hitPos * 0.3)) * 1.5) * 0.5 + 0.5;
    rockColor = mix(rockColor, vec3(0.06, 0.04, 0.03), bands * 0.3);

    // Lava veins
    vec3 lavaCol = mfLavaColor(lavaFlow, tension, chromaH);
    lavaCol = mix(lavaCol, lavaCol * palCol1 * 1.5, 0.1);

    vec3 matColor = mix(rockColor, lavaCol, lavaFlow);

    // Lava is self-emissive
    vec3 emissive = lavaCol * lavaFlow * 2.0 * fireIntensityMod;

    // Compose lighting
    vec3 lavaLightCol = mix(vec3(1.0, 0.4, 0.05), palCol1, 0.1);
    float lightIntensity = (0.3 + energy * 1.0) * fireIntensityMod;

    col = matColor * 0.02 * ambOcc; // minimal ambient
    col += matColor * lavaLightCol * lavaDiffuse * lightIntensity * shadow * 0.5;
    col += vec3(0.5, 0.3, 0.1) * lavaSpec * lightIntensity * shadow * 0.3;
    col += emissive;
    col += matColor * fresnelVal * 0.03;

    // Vocal warmth: expands warm glow
    float warmthRadius = 1.0 + vocalP * 2.0;
    float warmthFalloff = 1.0 / (1.0 + lavaDist * lavaDist / (warmthRadius * warmthRadius * 4.0));
    col += lavaLightCol * 0.02 * warmthFalloff * vocalP;

    // Rim lighting from eruption
    float rimLight = pow(1.0 - max(dot(viewDir, norm), 0.0), 4.0);
    col += lavaLightCol * rimLight * energy * 0.08 * lavaAtten;

    // Dynamic range
    col *= mix(0.8, 1.2, dynRange * (shadow * 0.5 + 0.5));

    // Distance fog: smoky atmosphere
    float fogAmount = 1.0 - exp(-terrainHitDist * 0.02);
    vec3 fogColor = mix(vec3(0.06, 0.03, 0.02), lavaLightCol * 0.08, energy * 0.3);
    col = mix(col, fogColor, fogAmount * 0.5);
  }

  // ─── Pyroclastic cloud ───
  float cloudMarchDist = terrainHitDist < 0.0 ? MAX_DIST : terrainHitDist;
  col += mfPyroclasticCloud(camOrigin, rd, cloudMarchDist, timeVal, energy, flux, slowE, palCol1);

  // ─── Ash particles ───
  col += mfAshParticles(camOrigin, rd, timeVal, energy, highs);

  // ─── Eruption flash on drum onset ───
  if (drumOnset > 0.3) {
    float flashIntensity = drumOnset * 0.15 * fireIntensityMod;
    col += vec3(1.0, 0.6, 0.2) * flashIntensity;
  }

  // ─── Icon emergence ───
  {
    float nf = fbm3(vec3(screenPos * 2.0, timeVal));
    vec3 iconLight = iconEmergence(screenPos, uTime, energy, bass,
      palCol1, palCol2, nf, uClimaxPhase, uSectionIndex);
    col += iconLight;
  }
  {
    float nf = fbm3(vec3(screenPos * 1.5, timeVal + 10.0));
    vec3 heroLight = heroIconEmergence(screenPos, uTime, energy, bass,
      palCol1, palCol2, nf, uSectionIndex);
    col += heroLight;
  }

  // ─── Vignette ───
  float vigScale = mix(0.28, 0.22, energy);
  float vignette = 1.0 - dot(screenPos * vigScale, screenPos * vigScale);
  vignette = smoothstep(0.0, 1.0, vignette);
  col = mix(vec3(0.01, 0.005, 0.002), col, vignette);

  // Shared color temperature for crossfade continuity
  col = applyTemperature(col);

  // ─── Post-processing ───
  col = applyPostProcess(col, vUv, screenPos);

  gl_FragColor = vec4(col, 1.0);
  ${mfDepthAlpha}
}
`;

// Legacy exports for backward compatibility
export const mountainSilhouetteVert = mountainFireVert;
export const mountainSilhouetteFrag = mountainFireFrag;
export const mountainSkyVert = mountainFireVert;
export const mountainSkyFrag = mountainFireFrag;
export const fireParticleVert = mountainFireVert;
export const fireParticleFrag = mountainFireFrag;
export const emberVert = mountainFireVert;
export const emberFrag = mountainFireFrag;
export const smokeVert = mountainFireVert;
export const smokeFrag = mountainFireFrag;

/** Compute fire color from chromaHue (0-1) for use in PointLight */
export function computeFireColor(chromaHue: number): [number, number, number] {
  const hue = 0.05 + chromaHue * 0.08;
  const h = hue * 6.0;
  const c = 0.95;
  const x = c * (1 - Math.abs(h % 2 - 1));
  let r = 0, g = 0, b = 0;
  if (h < 1) { r = c; g = x; }
  else if (h < 2) { r = x; g = c; }
  else if (h < 3) { g = c; b = x; }
  else if (h < 4) { g = x; b = c; }
  else if (h < 5) { r = x; b = c; }
  else { r = c; b = x; }
  return [r, g, b];
}
