/**
 * Ocean — raymarched ocean surface from above.
 * Volumetric water with subsurface scattering, rolling wave geometry,
 * foam patterns on crests, deep water color gradients, seabird silhouettes,
 * horizon with sky gradient.
 *
 * Audio reactivity:
 *   uBass             → swell height (calm → massive waves)
 *   uEnergy           → wave intensity, foam density, storm factor
 *   uDrumOnset        → foam/spray burst
 *   uVocalPresence    → bioluminescence intensity
 *   uHarmonicTension  → choppiness
 *   uBeatSnap         → wave pulse
 *   uSectionType      → jam=choppy whitecaps, space=glass-calm, solo=deep current
 *   uClimaxPhase      → massive wave eruption
 *   uSlowEnergy       → atmosphere, celestial pulse
 *   uHighs            → surface sparkle
 *   uMelodicPitch     → wave frequency modulation
 *   uChromaHue        → water/sky tint
 *   uPalettePrimary   → deep water hue
 *   uPaletteSecondary → sky/reflection hue
 *   uSpectralFlux     → wave turbulence
 *   uDynamicRange     → depth contrast
 *   uFlatness         → chop detail
 */

import { noiseGLSL } from "./noise";
import { sharedUniformsGLSL } from "./shared/uniforms.glsl";
import { buildPostProcessGLSL } from "./shared/postprocess.glsl";
import { buildRaymarchNormal, buildRaymarchAO } from "./shared/raymarching.glsl";

export const oceanVert = /* glsl */ `
varying vec2 vUv;
void main() {
  vUv = uv;
  gl_Position = vec4(position, 1.0);
}
`;

const oc2NormalGLSL = buildRaymarchNormal("oc2Map($P, timeVal, energy, bass, melPitch, tension, sJam, sSpace)", { eps: 0.05, name: "oc2Normal" });
const oc2AOGLSL = buildRaymarchAO("oc2Map($P, timeVal, energy, bass, melPitch, tension, sJam, sSpace)", { steps: 4, stepBase: 0.1, stepScale: 0.2, weightDecay: 0.6, finalMult: 1.5, name: "oc2AO" });

export const oceanFrag = /* glsl */ `
precision highp float;

${sharedUniformsGLSL}

${noiseGLSL}

${buildPostProcessGLSL({
  grainStrength: "normal",
  bloomEnabled: true,
  bloomThresholdOffset: -0.06,
  halationEnabled: true,
  caEnabled: true,
  lensDistortionEnabled: true,
  dofEnabled: true,
})}

varying vec2 vUv;

#define PI 3.14159265
#define TAU 6.28318530
#define MAX_STEPS 70
#define MAX_DIST 80.0
#define SURF_DIST 0.005

// ============================================================
// Prefixed utilities (oc2 = ocean)
// ============================================================
mat2 oc2Rot2(float a) {
  float c = cos(a), s = sin(a);
  return mat2(c, -s, s, c);
}

float oc2Hash(float n) { return fract(sin(n) * 43758.5453123); }
float oc2Hash2(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
vec3 oc2Hash3(float n) {
  return vec3(
    fract(sin(n * 127.1) * 43758.5453),
    fract(sin(n * 269.5) * 43758.5453),
    fract(sin(n * 419.2) * 43758.5453)
  );
}

// ============================================================
// Ocean wave height field
// ============================================================
float oc2WaveHeight(vec2 xz, float timeVal, float energy, float bass,
                    float melPitch, float tension, float sJam, float sSpace) {
  float storminess = clamp(energy + bass * 0.3, 0.0, 1.5);
  float waveSpeed = (0.3 + energy * 0.5) * (1.0 + sJam * 0.4 - sSpace * 0.6);
  float waveTime = timeVal * waveSpeed;
  float waveFreq = mix(0.08, 0.2, energy) + melPitch * 0.05 + sJam * 0.04;
  float waveAmp = mix(0.3, 4.0, storminess) * (1.0 + sJam * 0.3 - sSpace * 0.7);

  float h = 0.0;
  float freq = waveFreq;
  float amp = waveAmp;
  mat2 rot = mat2(0.8, 0.6, -0.6, 0.8);

  for (int i = 0; i < 6; i++) {
    float wave = sin(xz.x * freq + waveTime * (0.8 + float(i) * 0.15))
               + sin(xz.y * freq * 0.7 + waveTime * (0.6 + float(i) * 0.1));
    h += wave * amp;
    // Noise displacement for natural feel
    float nDisp = snoise(vec3(xz * freq * 0.3, waveTime * 0.1 + float(i) * 3.0));
    h += nDisp * amp * 0.3 * storminess;
    xz = rot * xz;
    freq *= 1.8;
    amp *= 0.5;
  }

  // Cross-chop from tension
  h += sin(xz.x * 0.5 + xz.y * 0.5 + waveTime * 2.0) * tension * 0.3;

  return h;
}

// ============================================================
// Ocean SDF map
// ============================================================
float oc2Map(vec3 pos, float timeVal, float energy, float bass,
             float melPitch, float tension, float sJam, float sSpace) {
  float waterH = oc2WaveHeight(pos.xz, timeVal, energy, bass, melPitch, tension, sJam, sSpace);
  return pos.y - waterH;
}

// Normal & AO — generated by shared raymarching utilities
${oc2NormalGLSL}
${oc2AOGLSL}

// ============================================================
// Sky with horizon
// ============================================================
vec3 oc2Sky(vec3 rd, float energy, float slowE, vec3 sunDir, vec3 palCol1, vec3 palCol2) {
  float skyGrad = rd.y * 0.5 + 0.5;
  float storminess = clamp(energy + 0.2, 0.0, 1.5);

  vec3 horizonColor = mix(vec3(0.5, 0.4, 0.3), palCol2 * 0.6, 0.2);
  horizonColor = mix(horizonColor, vec3(0.15, 0.12, 0.1), storminess * 0.4);
  vec3 deepSkyColor = mix(vec3(0.02, 0.04, 0.12), vec3(0.05, 0.06, 0.15), slowE);

  vec3 sky = mix(horizonColor, deepSkyColor, skyGrad);

  // Sun/moon
  float sunDot = max(dot(rd, sunDir), 0.0);
  float celestialBright = mix(0.9, 0.15, storminess);
  sky += vec3(1.0, 0.92, 0.7) * pow(sunDot, 128.0) * celestialBright * 2.0;
  sky += vec3(1.0, 0.85, 0.6) * pow(sunDot, 16.0) * celestialBright * 0.3;

  // Clouds
  float cloudN = fbm3(vec3(rd.xz * 2.5 / max(rd.y, 0.03), uDynamicTime * 0.01));
  float cloudMask = smoothstep(0.05, 0.4, rd.y) * smoothstep(0.8, 0.4, rd.y);
  vec3 cloudColor = mix(horizonColor * 0.5, vec3(0.08, 0.07, 0.1), 0.5);
  sky = mix(sky, cloudColor, smoothstep(0.3, 0.6, cloudN) * cloudMask * storminess * 0.4);

  // Stars (calm only)
  float starVis = smoothstep(0.4, 0.0, storminess);
  if (starVis > 0.01 && rd.y > 0.1) {
    vec2 starUV = rd.xz / (rd.y + 0.001);
    float starH = oc2Hash2(floor(starUV * 80.0));
    if (starH > 0.9) {
      vec2 starF = fract(starUV * 80.0);
      float starDist = length(starF - 0.5);
      float twinkle = 0.6 + 0.4 * sin(uTime * 2.0 + starH * 50.0);
      sky += vec3(0.8, 0.85, 1.0) * smoothstep(0.03, 0.005, starDist) * twinkle * starVis * 0.4;
    }
  }

  // Horizon glow band
  float horizonGlow = exp(-pow(rd.y * 8.0, 2.0));
  sky += horizonColor * horizonGlow * 0.3;

  return sky;
}

// ============================================================
// Seabird silhouettes
// ============================================================
vec3 oc2Seabirds(vec3 ro, vec3 rd, float timeVal) {
  vec3 birds = vec3(0.0);
  for (int i = 0; i < 5; i++) {
    float fi = float(i);
    vec3 seed = oc2Hash3(fi * 5.7 + 2.0);
    float bTime = timeVal * 0.3 + seed.x * TAU;
    vec3 birdPos = vec3(
      sin(bTime) * 15.0 + seed.y * 10.0 - 5.0,
      12.0 + seed.z * 4.0 + sin(bTime * 2.0) * 0.5,
      10.0 + seed.x * 20.0
    );

    vec3 toB = birdPos - ro;
    float proj = dot(toB, rd);
    if (proj < 0.0) continue;
    vec3 closest = ro + rd * proj;
    float dist = length(closest - birdPos);

    // Wing flap
    float wingPhase = sin(timeVal * 3.0 + fi * 2.0);
    float wingSpan = 0.3;
    // Simplified: check as small sphere
    float birdSize = 0.15 + abs(wingPhase) * 0.1;
    float silhouette = smoothstep(birdSize * 2.0, birdSize * 0.5, dist);

    // Dark against sky
    birds += vec3(-0.2) * silhouette * 0.3;
  }
  return birds;
}

// ============================================================
// Volumetric subsurface scattering (in-water light)
// ============================================================
vec3 oc2Subsurface(vec3 hitPos, vec3 norm, vec3 sunDir, float energy,
                   vec3 palCol1, float timeVal) {
  float sss = max(dot(-norm, sunDir), 0.0);
  sss = pow(sss, 2.0) * 0.3;
  float causticN = fbm3(vec3(hitPos.xz * 0.1 + vec2(0.0, -timeVal * 0.05), timeVal * 0.05));
  causticN = pow(max(causticN * 0.5 + 0.5, 0.0), 3.0);
  vec3 sssColor = mix(vec3(0.0, 0.3, 0.2), palCol1 * 0.8, 0.3);
  return sssColor * (sss + causticN * 0.15) * (0.3 + energy * 0.7);
}

void main() {
  vec2 uv = vUv;
  vec2 aspect = vec2(uResolution.x / uResolution.y, 1.0);
  vec2 screenPos = (uv - 0.5) * aspect;

  float energy = clamp(uEnergy, 0.0, 1.0);
  float bass = clamp(uBass, 0.0, 1.0);
  float highs = clamp(uHighs, 0.0, 1.0);
  float onset = clamp(uDrumOnset, 0.0, 1.0);
  float slowE = clamp(uSlowEnergy, 0.0, 1.0);
  float chromaH = clamp(uChromaHue, 0.0, 1.0);
  float flux = clamp(uSpectralFlux, 0.0, 1.0);
  float vocalP = clamp(uVocalPresence, 0.0, 1.0);
  float melPitch = clamp(uMelodicPitch, 0.0, 1.0);
  float tension = clamp(uHarmonicTension, 0.0, 1.0);
  float dynRange = clamp(uDynamicRange, 0.0, 1.0);
  float beatSnap = clamp(uBeatSnap, 0.0, 1.0);
  float flatness = clamp(uFlatness, 0.0, 1.0);

  float sectionT = uSectionType;
  float sJam = smoothstep(4.5, 5.5, sectionT) * (1.0 - step(5.5, sectionT));
  float sSpace = smoothstep(6.5, 7.5, sectionT);
  float sSolo = smoothstep(3.5, 4.5, sectionT) * (1.0 - step(4.5, sectionT));
  float sChorus = smoothstep(1.5, 2.5, sectionT) * (1.0 - step(2.5, sectionT));

  float isClimax = step(1.5, uClimaxPhase) * step(uClimaxPhase, 3.5);
  float climaxBoost = isClimax * uClimaxIntensity;

  float timeVal = uDynamicTime * 0.1;
  float storminess = clamp(energy + bass * 0.3, 0.0, 1.5);

  // Palette
  float hue1 = uPalettePrimary + chromaH * 0.05;
  float hue2 = uPaletteSecondary + chromaH * 0.04;
  float palSat = mix(0.5, 0.9, slowE) * uPaletteSaturation;
  vec3 palCol1 = hsv2rgb(vec3(hue1, palSat, mix(0.3, 0.6, energy)));
  vec3 palCol2 = hsv2rgb(vec3(hue2, palSat * 0.7, mix(0.4, 0.7, energy)));

  // Camera: hovering above ocean
  float camH = 6.0 + sin(uTime * 0.04) * 1.5;
  vec3 camOrigin = vec3(sin(uTime * 0.02) * 5.0, camH, uTime * 0.3);
  vec3 camTarget = camOrigin + vec3(0.0, -3.0, 10.0);
  vec3 camForward = normalize(camTarget - camOrigin);
  vec3 camWorldUp = vec3(0.0, 1.0, 0.0);
  vec3 camRt = normalize(cross(camForward, camWorldUp));
  vec3 camUpV = cross(camRt, camForward);

  vec3 rd = normalize(screenPos.x * camRt + screenPos.y * camUpV + 1.5 * camForward);

  // Sun position
  vec3 sunDir = normalize(vec3(0.4, 0.3, 0.5));

  // ─── Raymarching ───
  float marchDist = 0.0;
  float waterHitDist = -1.0;

  for (int i = 0; i < MAX_STEPS; i++) {
    vec3 pos = camOrigin + rd * marchDist;
    float d = oc2Map(pos, timeVal, energy, bass, melPitch, tension, sJam, sSpace);
    if (d < SURF_DIST) {
      waterHitDist = marchDist;
      break;
    }
    marchDist += d * 0.6;
    if (marchDist > MAX_DIST) break;
  }

  vec3 col;

  if (waterHitDist < 0.0) {
    // Sky
    col = oc2Sky(rd, energy, slowE, sunDir, palCol1, palCol2);
    // Seabird silhouettes
    col += oc2Seabirds(camOrigin, rd, timeVal);
  } else {
    vec3 hitPos = camOrigin + rd * waterHitDist;
    vec3 norm = oc2Normal(hitPos);
    float ambOcc = oc2AO(hitPos, norm);

    // Diffuse
    float diffuse = max(dot(norm, sunDir), 0.0) * 0.5 + 0.5;

    // Specular
    vec3 viewDir = normalize(camOrigin - hitPos);
    vec3 halfDir = normalize(sunDir + viewDir);
    float specular = pow(max(dot(norm, halfDir), 0.0), 64.0);

    // Fresnel
    float fresnelVal = pow(1.0 - max(dot(viewDir, norm), 0.0), 3.5);

    // Water base color
    vec3 deepWater = mix(vec3(0.02, 0.06, 0.12), palCol1 * 0.3, 0.15);
    vec3 shallowWater = mix(vec3(0.05, 0.15, 0.2), palCol2 * 0.4, 0.1);
    deepWater = mix(deepWater, vec3(0.02, 0.04, 0.10), sSpace * 0.4);

    float waveH = oc2WaveHeight(hitPos.xz, timeVal, energy, bass, melPitch, tension, sJam, sSpace);
    float maxWaveH = mix(0.5, 4.0, storminess);
    float surfaceShade = smoothstep(-maxWaveH, maxWaveH, waveH);
    vec3 waterColor = mix(deepWater, shallowWater, surfaceShade * 0.6);

    // Subsurface scattering
    vec3 sss = oc2Subsurface(hitPos, norm, sunDir, energy, palCol1, timeVal);
    waterColor += sss;

    // Sky reflection
    vec3 reflDir = reflect(rd, norm);
    vec3 skyRefl = oc2Sky(reflDir, energy, slowE, sunDir, palCol1, palCol2);
    waterColor = mix(waterColor, skyRefl, fresnelVal * 0.65);

    // Foam on crests
    float foamMask = smoothstep(maxWaveH * 0.4, maxWaveH * 0.85, waveH);
    float foamBoost = 1.0 + sJam * 0.5 - sSpace * 0.7;
    float foamAmount = foamMask * (onset * 0.6 + storminess * 0.4 + energy * 0.3) * clamp(foamBoost, 0.0, 2.0);
    float foamN1 = snoise(vec3(hitPos.xz * 0.1, timeVal * 0.15));
    float foamN2 = snoise(vec3(hitPos.xz * 0.3, timeVal * 0.2 + 10.0));
    foamAmount *= smoothstep(-0.1, 0.4, foamN1 * 0.6 + foamN2 * 0.4);
    foamAmount += pow(max(foamN2, 0.0), 4.0) * energy * 0.2 * foamMask;
    foamAmount = clamp(foamAmount, 0.0, 1.0);
    vec3 foamColor = mix(vec3(0.7, 0.75, 0.8), vec3(0.92, 0.95, 1.0), smoothstep(0.3, 0.8, foamAmount));
    waterColor = mix(waterColor, foamColor, foamAmount * 0.65);

    // Surface sparkle
    float sparkle = smoothstep(0.9, 0.95, snoise(vec3(hitPos.xz * 8.0, uDynamicTime * 0.4)));
    waterColor += vec3(1.0, 0.95, 0.85) * sparkle * highs * 0.4 * (1.0 - storminess * 0.5);

    // Bioluminescence on vocal presence
    if (vocalP > 0.1) {
      float bioGate = smoothstep(0.1, 0.5, vocalP) * (1.0 - storminess * 0.6);
      float bioN = sin(hitPos.x * 0.3 + snoise(vec3(hitPos.xz * 0.1, timeVal * 0.04)) * 3.0 + timeVal * 0.3)
                 * cos(hitPos.z * 0.4 + timeVal * 0.2);
      bioN = smoothstep(0.3, 0.8, bioN * 0.5 + 0.5);
      vec3 bioColor = mix(hsv2rgb(vec3(hue1, 0.8, 0.9)), hsv2rgb(vec3(hue2, 0.7, 0.8)), bioN);
      waterColor += bioColor * bioN * bioGate * 0.2;
    }

    // Compose
    vec3 sunColor = vec3(1.0, 0.92, 0.75);
    float celestialBright = mix(0.8, 0.2, storminess);

    col = waterColor * ambOcc;
    col += waterColor * sunColor * diffuse * celestialBright * 0.3;
    col += vec3(0.8, 0.85, 1.0) * specular * celestialBright * 0.4;

    // Chorus: sparkling highlight
    col += vec3(0.04, 0.06, 0.1) * sChorus * surfaceShade * 0.4;
    // Solo: deep undertone
    col += vec3(0.0, 0.02, 0.05) * sSolo * (1.0 - surfaceShade) * 0.4;

    // Distance fog toward horizon
    float fogDist = waterHitDist * 0.005;
    float fogAmount = 1.0 - exp(-fogDist * fogDist);
    vec3 fogColor = mix(
      hsv2rgb(vec3(hue1, palSat * 0.15, 0.06)),
      hsv2rgb(vec3(hue2, palSat * 0.1, 0.08)),
      0.5
    );
    col = mix(col, fogColor, clamp(fogAmount, 0.0, 0.7));
  }

  // ─── Icon emergence ───
  {
    float nf = fbm3(vec3(screenPos * 2.0, timeVal));
    vec3 iconLight = iconEmergence(screenPos, uTime, energy, bass,
      palCol1, palCol2, nf, uClimaxPhase, uSectionIndex);
    col += iconLight;
  }
  {
    float nf = fbm3(vec3(screenPos * 1.5, timeVal + 10.0));
    vec3 heroLight = heroIconEmergence(screenPos, uTime, energy, bass,
      palCol1, palCol2, nf, uSectionIndex);
    col += heroLight;
  }

  // ─── Vignette ───
  float vigScale = mix(0.28, 0.22, energy);
  float vignette = 1.0 - dot(screenPos * vigScale, screenPos * vigScale);
  vignette = smoothstep(0.0, 1.0, vignette);
  col = mix(vec3(0.01, 0.02, 0.04), col, vignette);

  // ─── Post-processing ───
  col = applyPostProcess(col, vUv, screenPos);

  gl_FragColor = vec4(col, 1.0);
}
`;

// Legacy exports for backward compatibility
export const oceanWaterVert = oceanVert;
export const oceanWaterFrag = oceanFrag;
export const oceanSkyVert = oceanVert;
export const oceanSkyFrag = oceanFrag;
export const oceanCelestialVert = oceanVert;
export const oceanCelestialFrag = oceanFrag;
export const oceanFoamVert = oceanVert;
export const oceanFoamFrag = oceanFrag;
export const oceanBioVert = oceanVert;
export const oceanBioFrag = oceanFrag;
