/**
 * Transition Affinity Map — pure data, no scene component imports.
 *
 * Which shaders crossfade well together. Used by SceneRouter for energy-aware
 * morphing AND by build-time precompute scripts that need this data without
 * pulling in React/scene-component code.
 */

import type { VisualMode } from "../data/types";

export const TRANSITION_AFFINITY: Partial<Record<VisualMode, VisualMode[]>> = {
  liquid_light: ["protean_clouds", "protean_clouds", "inferno"],
  concert_lighting: ["inferno", "protean_clouds", "protean_clouds"],
  deep_ocean: ["aurora", "cosmic_voyage", "cosmic_voyage"],
  cosmic_voyage: ["cosmic_voyage", "deep_ocean", "aurora"],
  inferno: ["inferno", "protean_clouds", "protean_clouds"],
  oil_projector: ["protean_clouds", "lo_fi_grain", "vintage_film"],
  tie_dye: ["protean_clouds", "inferno", "inferno"],
  aurora: ["deep_ocean", "cosmic_voyage", "cosmic_voyage"],
  particle_nebula: ["cosmic_dust", "cosmic_voyage", "aurora"],
  cosmic_dust: ["cosmic_voyage", "deep_ocean", "cosmic_voyage"],
  lo_fi_grain: ["protean_clouds", "vintage_film", "deep_ocean"],
  vintage_film: ["protean_clouds", "lo_fi_grain", "deep_ocean"],
  stark_minimal: ["lo_fi_grain", "vintage_film", "cosmic_dust"],
  crystal_cavern: ["deep_ocean", "aurora", "cosmic_dust"],
  fluid_light: ["protean_clouds", "protean_clouds", "protean_clouds"],
  void_light: ["deep_ocean", "cosmic_voyage", "cosmic_voyage"],
  fluid_2d: ["protean_clouds", "fluid_light", "protean_clouds"],
  spectral_analyzer: ["inferno", "inferno", "inferno"],
  particle_swarm: ["cosmic_dust", "cosmic_voyage", "aurora"],
  crystalline_growth: ["cosmic_voyage", "deep_ocean", "aurora"],
  climax_surge: ["inferno", "inferno", "deep_ocean"],
  kaleidoscope: ["protean_clouds", "protean_clouds", "cosmic_voyage"],
  fractal_zoom: ["cosmic_voyage", "cosmic_voyage", "cosmic_voyage"],
  sacred_geometry: ["cosmic_voyage", "aurora", "cosmic_voyage"],
  reaction_diffusion: ["fluid_2d", "protean_clouds", "protean_clouds"],
  mandala_engine: ["cosmic_voyage", "cosmic_voyage", "cosmic_voyage"],
  fractal_flames: ["inferno", "protean_clouds", "protean_clouds"],
  feedback_recursion: ["protean_clouds", "cosmic_voyage", "deep_ocean", "deep_ocean", "cosmic_voyage", "cosmic_voyage", "cosmic_voyage"],
  truchet_tiling: ["cosmic_voyage", "mandala_engine", "cosmic_voyage"],
  diffraction_rings: ["aurora", "cosmic_voyage", "deep_ocean"],
  plasma_field: ["protean_clouds", "protean_clouds", "deep_ocean"],
  voronoi_flow: ["cosmic_voyage", "cosmic_voyage", "protean_clouds"],
  stained_glass: ["cosmic_voyage", "protean_clouds", "cosmic_voyage"],
  electric_arc: ["inferno", "inferno", "aurora"],
  morphogenesis: ["deep_ocean", "fluid_2d", "protean_clouds"],
  neural_web: ["inferno", "cosmic_voyage", "cosmic_voyage"],
  smoke_rings: ["deep_ocean", "aurora", "protean_clouds"],
  aurora_curtains: ["aurora", "deep_ocean", "cosmic_voyage"],
  digital_rain: ["deep_ocean", "lo_fi_grain", "inferno"],
  lava_flow: ["inferno", "inferno", "cosmic_voyage"],
  mycelium_network: ["deep_ocean", "cosmic_voyage", "deep_ocean"],
  ink_wash: ["deep_ocean", "vintage_film", "deep_ocean"],
  coral_reef: ["deep_ocean", "aurora", "cosmic_voyage"],
  solar_flare: ["inferno", "inferno", "inferno"],
  galaxy_spiral: ["cosmic_voyage", "cosmic_dust", "cosmic_voyage"],
  warp_field: ["deep_ocean", "cosmic_voyage", "void_light"],
  signal_decay: ["cosmic_voyage", "lo_fi_grain", "vintage_film"],
  databend: ["cosmic_voyage", "deep_ocean", "lo_fi_grain"],
  volumetric_clouds: ["aurora", "deep_ocean", "cosmic_voyage"],
  volumetric_smoke: ["inferno", "protean_clouds", "lo_fi_grain"],
  volumetric_nebula: ["cosmic_voyage", "cosmic_voyage", "cosmic_voyage"],
  river: ["deep_ocean", "aurora", "deep_ocean", "volumetric_clouds"],
  space_travel: ["cosmic_voyage", "aurora", "volumetric_nebula", "void_light"],
  mountain_fire: ["inferno", "inferno", "deep_ocean", "aurora"],
  flower_field: ["aurora", "deep_ocean", "protean_clouds", "cosmic_voyage"],
  forest: ["aurora", "deep_ocean", "deep_ocean", "volumetric_clouds"],
  ocean: ["deep_ocean", "aurora", "river", "deep_ocean"],
  desert_road: ["inferno", "inferno", "mountain_fire", "protean_clouds"],
  campfire: ["aurora", "protean_clouds", "volumetric_smoke", "inferno"],
  rain_street: ["deep_ocean", "deep_ocean", "protean_clouds", "cosmic_voyage"],
  aurora_sky: ["aurora", "cosmic_voyage", "deep_ocean", "volumetric_nebula"],
  storm: ["inferno", "inferno", "inferno", "rain_street"],
  canyon: ["deep_ocean", "aurora", "cosmic_voyage", "cosmic_voyage"],
  liquid_mandala: ["cosmic_voyage", "cosmic_voyage", "mandala_engine", "protean_clouds"],
  bioluminescence: ["deep_ocean", "deep_ocean", "deep_ocean", "aurora"],
  neon_grid: ["inferno", "inferno", "deep_ocean", "cosmic_voyage"],
  warm_nebula: ["deep_ocean", "aurora", "volumetric_clouds", "campfire"],
  prism_refraction: ["deep_ocean", "cosmic_voyage", "aurora", "cosmic_voyage"],
  cellular_automata: ["deep_ocean", "deep_ocean", "protean_clouds", "cosmic_voyage"],
  acid_melt: ["protean_clouds", "protean_clouds", "protean_clouds", "cosmic_voyage"],
  blacklight_glow: ["deep_ocean", "deep_ocean", "void_light", "cosmic_dust"],
  spinning_spiral: ["cosmic_voyage", "mandala_engine", "protean_clouds"],
  liquid_projector: ["protean_clouds", "protean_clouds", "protean_clouds", "vintage_film"],
  protean_clouds: ["terrapin_nebula", "dark_star_void", "volumetric_clouds", "star_nest"],
  morning_dew_fog: ["volumetric_clouds", "wharf_rat_storm", "scarlet_golden_haze", "nimitz_aurora"],
  dark_star_void: ["star_nest", "terrapin_nebula", "cosmic_voyage", "volumetric_nebula"],
  fire_mountain_smoke: ["combustible_voronoi", "inferno", "st_stephen_lightning", "inferno"],
  estimated_prophet_mist: ["seascape", "deep_ocean", "wharf_rat_storm", "ocean"],
  wharf_rat_storm: ["morning_dew_fog", "estimated_prophet_mist", "rain_street", "storm"],
  scarlet_golden_haze: ["creation", "morning_dew_fog", "nimitz_aurora", "protean_clouds"],
  st_stephen_lightning: ["fire_mountain_smoke", "combustible_voronoi", "inferno", "storm"],
  terrapin_nebula: ["dark_star_void", "protean_clouds", "star_nest", "volumetric_nebula"],
  star_nest: ["dark_star_void", "terrapin_nebula", "cosmic_voyage", "cosmic_voyage"],
  seascape: ["estimated_prophet_mist", "deep_ocean", "ocean", "river"],
  combustible_voronoi: ["fire_mountain_smoke", "inferno", "inferno", "st_stephen_lightning"],
  nimitz_aurora: ["aurora", "protean_clouds", "scarlet_golden_haze", "morning_dew_fog"],
  creation: ["protean_clouds", "scarlet_golden_haze", "protean_clouds", "cosmic_voyage"],
  fractal_temple: ["cosmic_voyage", "cosmic_voyage", "volumetric_nebula", "dark_star_void"],
  highway_horizon: ["cosmic_railroad", "desert_cantina", "campfire_embers", "protean_clouds"],
  honeycomb_cathedral: ["stained_glass_dissolution", "aviary_canopy", "memorial_drift", "aurora"],
  campfire_embers: ["porch_twilight", "desert_cantina", "memorial_drift", "protean_clouds"],
  neon_casino: ["dance_floor_prism", "clockwork_temple", "bloom_explosion", "inferno"],
  storm_vortex: ["earthquake_fissure", "canyon_chase", "inferno", "storm"],
  psychedelic_garden: ["aviary_canopy", "bloom_explosion", "cosmic_railroad", "protean_clouds"],
  cosmic_railroad: ["highway_horizon", "event_horizon", "cosmic_voyage", "protean_clouds"],
  desert_cantina: ["campfire_embers", "canyon_chase", "highway_horizon", "protean_clouds"],
  earthquake_fissure: ["storm_vortex", "canyon_chase", "inferno", "storm"],
  mobius_amphitheater: ["event_horizon", "cosmic_railroad", "cosmic_voyage", "protean_clouds"],
  memorial_drift: ["porch_twilight", "honeycomb_cathedral", "stained_glass_dissolution", "aurora"],
  boxcar_tunnel: ["locomotive_engine", "highway_horizon", "desert_cantina", "protean_clouds"],
  aviary_canopy: ["psychedelic_garden", "honeycomb_cathedral", "bloom_explosion", "aurora"],
  clockwork_temple: ["neon_casino", "dance_floor_prism", "bloom_explosion", "inferno"],
  event_horizon: ["cosmic_railroad", "mobius_amphitheater", "cosmic_voyage", "dark_star_void"],
  canyon_chase: ["desert_cantina", "earthquake_fissure", "storm_vortex", "inferno"],
  porch_twilight: ["memorial_drift", "campfire_embers", "honeycomb_cathedral", "aurora"],
  bloom_explosion: ["psychedelic_garden", "neon_casino", "dance_floor_prism", "protean_clouds"],
  locomotive_engine: ["boxcar_tunnel", "canyon_chase", "highway_horizon", "inferno"],
  dance_floor_prism: ["neon_casino", "clockwork_temple", "bloom_explosion", "inferno"],
  stained_glass_dissolution: ["honeycomb_cathedral", "memorial_drift", "porch_twilight", "aurora"],
};
