/**
 * EffectScheduleContext — provides per-frame effect mode/intensity from
 * the pre-computed manifest effect schedule.
 *
 * The effect schedule is generated by generate-full-manifest.ts and extracted
 * via extract-effect-schedule.ts into lightweight per-song JSON files.
 *
 * FullscreenQuad and MultiPassQuad subscribe to this context to set
 * uEffectMode/uEffectIntensity uniforms on the effect post-pass.
 */

import React, { createContext, useContext, useMemo } from "react";
import { useCurrentFrame } from "remotion";

/** Per-frame effect data from the manifest */
export interface EffectScheduleFrame {
  /** 0=none, 1-14=post-process effect mode */
  effectMode: number;
  /** 0-1 intensity of the post-process effect */
  effectIntensity: number;
  /** 0=none, 1-10=composited effect mode */
  compositedMode: number;
  /** 0-1 intensity of the composited effect */
  compositedIntensity: number;
}

/** Full effect schedule for a song */
export interface EffectSchedule {
  trackId: string;
  fps: number;
  frames: EffectScheduleFrame[];
}

/** Current-frame effect state exposed via context */
export interface EffectState {
  effectMode: number;
  effectIntensity: number;
  compositedMode: number;
  compositedIntensity: number;
}

const EMPTY_STATE: EffectState = {
  effectMode: 0,
  effectIntensity: 0,
  compositedMode: 0,
  compositedIntensity: 0,
};

const EffectScheduleCtx = createContext<EffectState>(EMPTY_STATE);

interface ProviderProps {
  schedule: EffectSchedule | null;
  children: React.ReactNode;
}

/**
 * Wraps children in a per-frame effect state provider.
 * Reads the current Remotion frame and looks up the corresponding
 * effect data from the schedule.
 */
export const EffectScheduleProvider: React.FC<ProviderProps> = ({
  schedule,
  children,
}) => {
  const frame = useCurrentFrame();

  const state = useMemo<EffectState>(() => {
    if (!schedule || !schedule.frames || schedule.frames.length === 0) {
      return EMPTY_STATE;
    }
    const idx = Math.min(Math.max(0, frame), schedule.frames.length - 1);
    const f = schedule.frames[idx];
    return {
      effectMode: f.effectMode,
      effectIntensity: f.effectIntensity,
      compositedMode: f.compositedMode,
      compositedIntensity: f.compositedIntensity,
    };
  }, [schedule, frame]);

  return (
    <EffectScheduleCtx.Provider value={state}>
      {children}
    </EffectScheduleCtx.Provider>
  );
};

/** Hook to read the current frame's effect state */
export function useEffectSchedule(): EffectState {
  return useContext(EffectScheduleCtx);
}
