import { describe, it, expect } from "vitest";
import {
  isVenetaShow,
  getVenetaSongIdentity,
  VENETA_SONG_IDENTITIES,
  VENETA_SHOW_DATE,
} from "./veneta-routing.js";

describe("veneta-routing", () => {
  it("isVenetaShow matches the canonical date", () => {
    expect(isVenetaShow(VENETA_SHOW_DATE)).toBe(true);
    expect(isVenetaShow("1977-05-08")).toBe(false);
    expect(isVenetaShow(undefined)).toBe(false);
  });

  it("returns identity for known song titles", () => {
    const id = getVenetaSongIdentity("Sugaree");
    expect(id).toBeDefined();
    expect(id?.preferredModes?.length ?? 0).toBeGreaterThan(0);
  });

  it("returns undefined for unknown songs", () => {
    expect(getVenetaSongIdentity("Some Random Song That Doesnt Exist")).toBeUndefined();
  });

  it("loads from data/shows/.../routing.json when present (not via window)", () => {
    // Smoke: importing this module shouldn't throw; lookup should succeed.
    // The JSON file is auto-generated by scripts/extract-show-routing.mts.
    const id = getVenetaSongIdentity("promisedland");
    expect(id).toBeDefined();
    // Spot-check a value also present in the JSON.
    expect(id?.palette?.primary).toBe(35);
  });

  it("inline VENETA_SONG_IDENTITIES still exposes 22 songs", () => {
    expect(Object.keys(VENETA_SONG_IDENTITIES).length).toBeGreaterThanOrEqual(20);
  });
});
